# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02data/init.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/02data/init.ipynb 1
__all__ = None
del __all__

# %% ../../nbs/02data/init.ipynb 2
#| eval: false
import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'infra',
        'transforms',
        'vtab_1k',
    },
    submod_attrs={
        'infra': [
            'CIFAR100DataModule',
            'CIFAR10DataModule',
            'ClassificationDataConfig',
            'ClassificationDataModule',
            'FashionMNISTDataModule',
            'KMNISTTDataModule',
            'MNISTDataModule',
            'QMNISTDataModule',
            'TorchVisionDataModule',
            'cls_names_of',
            'dataloader_to_arrays',
            'simple_pixel_flatten_transform',
            'sksplit_for_torch',
        ],
        'transforms': [
            'CutoutPIL',
        ],
        'vtab_1k': [
            'CutoutPIL',
        ],
    },
)

__all__ = ['CIFAR100DataModule', 'CIFAR10DataModule',
           'ClassificationDataConfig', 'ClassificationDataModule', 'CutoutPIL',
           'FashionMNISTDataModule', 'KMNISTTDataModule', 'MNISTDataModule',
           'QMNISTDataModule', 'TorchVisionDataModule', 'cls_names_of',
           'dataloader_to_arrays', 'infra', 'simple_pixel_flatten_transform',
           'sksplit_for_torch', 'transforms', 'vtab_1k']
