"""https://google-research.github.io/task_adaptation/"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../src/notebooks/02data/vtab_1k.ipynb.

# %% auto 0
__all__ = []

# %% ../../src/notebooks/02data/vtab_1k.ipynb 4
from .from_ssf.vtab import VtabSplit, VtabDataset
