"""主训练脚本入口，调用各模块进行模型训练"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/notebooks/05_main (example running script).ipynb.

# %% auto 0
__all__ = ['config']

# %% ../src/notebooks/05_main (example running script).ipynb 5
from .auto.experiment.infra import run_with_config
from boguan_yuequ.benchmarking import pe_list_tiny_for_all_size, backbone_names
from .nucleus import ClassificationTask, ClassificationTaskConfig

# %% ../src/notebooks/05_main (example running script).ipynb 7
config = ClassificationTaskConfig()
config.yuequ = "wave_high_shoulder"
# config.yuequ = "wave_high_ladder"
config.cls_model_config.checkpoint = backbone_names[2]
config.dataset_config.batch_size = 128

# %% ../src/notebooks/05_main (example running script).ipynb 15
#| eval: false
config.experiment_project = "Homogeneous dwarf model is all you need for tuning pretrained giant model." 
config.experiment_task = "Auto LR Range Test for wave_high_shoulder"
run_with_config(config,
                need_reproduce=True, 
                profile = True,
                
                batch_size = -1,
                search_learning_rate=True, 
                
                max_epochs = 100,
                    )
