# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NamableClassify',
                'doc_host': 'https://2catycm.github.io',
                'git_url': 'https://github.com/2catycm/NamableClassify',
                'lib_path': 'namable_classify'},
  'syms': { 'namable_classify.auto.examples.full_finetune': {},
            'namable_classify.auto.experiment.infra': {},
            'namable_classify.auto.experiment.mutiple': {},
            'namable_classify.auto.experiment.single': {},
            'namable_classify.auto.run': {},
            'namable_classify.data.transforms': { 'namable_classify.data.transforms.CutoutPIL': ( 'data_transforms.html#cutoutpil',
                                                                                                  'namable_classify/data/transforms.py'),
                                                  'namable_classify.data.transforms.CutoutPIL.__call__': ( 'data_transforms.html#cutoutpil.__call__',
                                                                                                           'namable_classify/data/transforms.py'),
                                                  'namable_classify.data.transforms.CutoutPIL.__init__': ( 'data_transforms.html#cutoutpil.__init__',
                                                                                                           'namable_classify/data/transforms.py')},
            'namable_classify.help': {},
            'namable_classify.infra': {},
            'namable_classify.metrics': { 'namable_classify.metrics.compute_classification_metrics': ( 'metrics.html#compute_classification_metrics',
                                                                                                       'namable_classify/metrics.py'),
                                          'namable_classify.metrics.draw_classification_metrics': ( 'metrics.html#draw_classification_metrics',
                                                                                                    'namable_classify/metrics.py'),
                                          'namable_classify.metrics.get_top_bottom_k_classes': ( 'metrics.html#get_top_bottom_k_classes',
                                                                                                 'namable_classify/metrics.py'),
                                          'namable_classify.metrics.list_i_terms': ( 'metrics.html#list_i_terms',
                                                                                     'namable_classify/metrics.py'),
                                          'namable_classify.metrics.per_class_accuracy': ( 'metrics.html#per_class_accuracy',
                                                                                           'namable_classify/metrics.py')},
            'namable_classify.nucleus': { 'namable_classify.nucleus.ClassificationModelConfig': ( 'nucleus (classification core '
                                                                                                  'api).html#classificationmodelconfig',
                                                                                                  'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationModelConfig.get_cls_model': ( 'nucleus (classification '
                                                                                                                'core '
                                                                                                                'api).html#classificationmodelconfig.get_cls_model',
                                                                                                                'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask': ( 'nucleus (classification core '
                                                                                           'api).html#classificationtask',
                                                                                           'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.__init__': ( 'nucleus (classification core '
                                                                                                    'api).html#classificationtask.__init__',
                                                                                                    'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.compute_model_logits': ( 'nucleus (classification '
                                                                                                                'core '
                                                                                                                'api).html#classificationtask.compute_model_logits',
                                                                                                                'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.configure_optimizers': ( 'nucleus (classification '
                                                                                                                'core '
                                                                                                                'api).html#classificationtask.configure_optimizers',
                                                                                                                'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.evaluation_step': ( 'nucleus (classification core '
                                                                                                           'api).html#classificationtask.evaluation_step',
                                                                                                           'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.forward': ( 'nucleus (classification core '
                                                                                                   'api).html#classificationtask.forward',
                                                                                                   'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.forward_loss': ( 'nucleus (classification core '
                                                                                                        'api).html#classificationtask.forward_loss',
                                                                                                        'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.get_logger_with_type': ( 'nucleus (classification '
                                                                                                                'core '
                                                                                                                'api).html#classificationtask.get_logger_with_type',
                                                                                                                'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_evaluation_epoch_end': ( 'nucleus '
                                                                                                                   '(classification core '
                                                                                                                   'api).html#classificationtask.on_evaluation_epoch_end',
                                                                                                                   'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_evaluation_epoch_start': ( 'nucleus '
                                                                                                                     '(classification core '
                                                                                                                     'api).html#classificationtask.on_evaluation_epoch_start',
                                                                                                                     'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_test_epoch_end': ( 'nucleus (classification core '
                                                                                                             'api).html#classificationtask.on_test_epoch_end',
                                                                                                             'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_test_epoch_start': ( 'nucleus (classification '
                                                                                                               'core '
                                                                                                               'api).html#classificationtask.on_test_epoch_start',
                                                                                                               'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_validation_epoch_end': ( 'nucleus '
                                                                                                                   '(classification core '
                                                                                                                   'api).html#classificationtask.on_validation_epoch_end',
                                                                                                                   'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.on_validation_epoch_start': ( 'nucleus '
                                                                                                                     '(classification core '
                                                                                                                     'api).html#classificationtask.on_validation_epoch_start',
                                                                                                                     'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.test_step': ( 'nucleus (classification core '
                                                                                                     'api).html#classificationtask.test_step',
                                                                                                     'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.training_step': ( 'nucleus (classification core '
                                                                                                         'api).html#classificationtask.training_step',
                                                                                                         'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTask.validation_step': ( 'nucleus (classification core '
                                                                                                           'api).html#classificationtask.validation_step',
                                                                                                           'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.ClassificationTaskConfig': ( 'nucleus (classification core '
                                                                                                 'api).html#classificationtaskconfig',
                                                                                                 'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.HuggingfaceModel': ( 'nucleus (classification core '
                                                                                         'api).html#huggingfacemodel',
                                                                                         'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.HuggingfaceModel.__init__': ( 'nucleus (classification core '
                                                                                                  'api).html#huggingfacemodel.__init__',
                                                                                                  'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.HuggingfaceModel.forward': ( 'nucleus (classification core '
                                                                                                 'api).html#huggingfacemodel.forward',
                                                                                                 'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.nn.Module.see_grad_norm': ( 'nucleus (classification core '
                                                                                                'api).html#nn.module.see_grad_norm',
                                                                                                'namable_classify/nucleus.py'),
                                          'namable_classify.nucleus.nn.Module.see_params_norm': ( 'nucleus (classification core '
                                                                                                  'api).html#nn.module.see_params_norm',
                                                                                                  'namable_classify/nucleus.py')}}}
