"""主要定义与任务相关的核心组件和配置"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ClassificationTaskConfig']

# %% ../nbs/00_core.ipynb 5
import lightning as L
from pydantic import BaseModel
from .data import ClassificationDataConfig

class ClassificationTaskConfig(BaseModel):
    # vtab_dir: str = "/home/ai_pitch_perfector/datasets/vtab-1k/"
    # subset_name: str = "cifar"
    # initial_batch_size: int = 64
    # initial_learning_rate: int = 3e-4
    # experiment_index: int = 0  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 表示是第几次重复实验
    # label_smoothing: float = 0.1
    seed: int = 42
    backbone_name: str = 'vit-base-patch16-224'
    backbone_config: dict = {}
    dataset_config: ClassificationDataConfig = ClassificationDataConfig()
