"""本库的一些信息"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_help (library information).ipynb.

# %% auto 0
__all__ = ['lib_paths']

# %% ../nbs/00_help (library information).ipynb 4
import namable_classify
from scholarly_infrastructure.help import setup_paths, create_variables_from_dict, LibraryPaths
lib_paths:LibraryPaths = setup_paths(namable_classify)
create_variables_from_dict(lib_paths, globals())
