"""通用工具函数和路径设置"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_infra (utils reused among lib).ipynb.

# %% auto 0
__all__ = ['memory']

# %% ../nbs/00_infra (utils reused among lib).ipynb 6
from .help import runs_path, lib_paths

# %% ../nbs/00_infra (utils reused among lib).ipynb 8
import joblib
memory = joblib.Memory(location=runs_path/"joblib_cache", verbose=0)

# %% ../nbs/00_infra (utils reused among lib).ipynb 10
from scholarly_infrastructure.logging.nucleus import original_print, print, logger, Markdown

# %% ../nbs/00_infra (utils reused among lib).ipynb 14
from scholarly_infrastructure.logging.torch import inspect_model_parameters, num_of_total_parameters, num_of_trainable_parameters, print_trainable_parameters

# %% ../nbs/00_infra (utils reused among lib).ipynb 17
from scholarly_infrastructure.logging.torch import model_rich_tree, print_model_pretty

# %% ../nbs/00_infra (utils reused among lib).ipynb 20
from scholarly_infrastructure.nucleus import MuteWarnings, ensure_array, default_on_exception, append_dict_list
